### ISSUE TITLE
The IDEA .*ignore plugin should include .idea folder in autogenerated .ignore file, as it does for project folders of other IDEs (Spyder, Rope).

### ISSUE THREAD

**Issue by domeniconappo** [JetBrains/idea-gitignore#540]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

_Developer must remember to add .idea folder in ignore file._

### Steps to Reproduce

1. _Create project, integrate it with GIT and add a generated .gitignore file_
2. _Add and commit some changes_
3. _.idea folder is on repo while should have been ignored._

**Expected behavior:** _.idea folder should never be on repositories so it must be ignored_

**Actual behavior:** _Generated ignore file is not including .idea folder, while is including other IDEs (!!!) specific folders (e.g. Spyder stuff)_

**Reproduces how often:** _100%._

**Comment by SkySchulz** [comment]
Consider this as a configurable option and not a default. I prefer to commit common aspects of `.idea/**`, including dictionaries, and ignore only personal/local files in `.idea/`.

Proposed options:

```
(*) Ignore All
( ) Ignore Personal
( ) Ignore Custom
```

**Comment by hsz** [comment]
This cannot and even should not be implemented as a feature.
As @SkySchulz suggested a few options - it gets complicated and requires some user input anyway (prompt question or it'll get user confused because, he'll have to search a place where it can be changed).
Instead I can suggest you creating your own _user's template_ and simply use the same base `.gitignore` when project is created.
