### ISSUE TITLE
gitignored folders containing "ide" are not highlightes as ignored in the PhpStorm file tree.

### ISSUE THREAD

**Issue by foobar13372** [JetBrains/idea-gitignore#621]
Steps to reproduce:
* have a `.gitignore` file containung `*`
* have a file in folder named `contains-ide-string/file.txt`
* `git status` -> no changes
* PhpStorm file tree however: draws file.txt and folder in "tracked but unchanged" color (white in Darcula)

Expected: it drawes file and folder in "ignored" color (orange in Darcula)

**Comment by dmitriysmirnovjb** [comment]
Ignored files highlighting is provided by the IntelliJ itself since 2019.1. The .ignore plugin is not involved.
If you have any issue with highlighting - please report to https://youtrack.jetbrains.com/issues/IDEA

As a side note - I am not able to reproduce the behavior. 
Check if `git status --ignored` list the file.txt
Also, it could happen that the file is not yet saved to disk - check if File - Save All helps
