### ISSUE TITLE
Support global ignores

### ISSUE THREAD

**Issue by jaraco** [JetBrains/idea-gitignore#632]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet

### Description

Rather than copy ignores from each and every project I maintain, I keep a global ignores file at `~/.gitignore_global` and reference that file in my git config:

```
[core]
        excludesfile = /Users/jaraco/.gitignore_global
```

As a result, git now ignores irrelevant files across hundreds of projects I maintain.

Now I'd like for pycharm to honor these ignores, but it seems that the plugin ignores this setting (files ignored by git appear yellow in PyCharm).

Could you consider adding a setting to reflect the ignores as Git resolves them?

**OS:** macOS 10.15.5

**Comment by hsz** [comment]
`.gitignore` (Git) and `.hgignore` (Mercurial) support is already dropped by this plugin because IntelliJ-based IDEs since 2019.2+ natively support them.
Ref: [Support for VCS Ignores in IntelliJ IDEA and IntelliJ-based IDEs](https://blog.jetbrains.com/idea/2019/07/support-for-vcs-ignores-in-intellij-idea-and-intellij-based-ides/)
