### ISSUE TITLE
incompatible with IDEA 2020.3

### ISSUE THREAD

**Issue by BorzdeG** [JetBrains/idea-gitignore#637]
> Incompatible: requires IDE build 203 or older

**Comment by BorzdeG** [comment]
plugin (for those who do not want to collect himself): [idea-gitignore-3.2.3.203.zip](https://github.com/JetBrains/idea-gitignore/files/5265938/idea-gitignore-3.2.3.203.zip)

**Comment by ruurd** [comment]
Any ETA on this, @hsz? 2020.3 is out currently.

**Comment by hsz** [comment]
There are still a couple of issues to resolve, but I'm working on that. I hope to release it next week.

**Comment by ruurd** [comment]
@hsz is there any way we can help?

**Comment by hsz** [comment]
@ruurd Thanks, it's almost done as I just described it here: https://twitter.com/hszanowski/status/1335306406682103808
Tests are green, everything builds well – I just need to verify if everything works as previously since there was a giant refactoring done.

**Comment by Mereo4** [comment]
Still doesn't work. Someone found a provisional workaround (just below), but the plugin doesn't appear anymore on the plugins panel of JetBrains IDE.

> Please find folder *\IntelliJIdea2020.3\plugins\idea-gitignore, open ./lib/idea-gitignore-3.2.3.202.jar and change "until-build" in /META-INF/plugin.xml, restart your IDEA. <idea-version since-build="202" until-build="203.*"/>

**Comment by BorzdeG** [comment]
@Mereo4 We are waiting for the release to be released. In the meantime, you can manually install the fix that I applied above - I do not feel any problems with it yet
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2332528/101459284-1b660a00-3949-11eb-8bee-9ac47e52374f.png">

**Comment by Mereo4** [comment]
Yes, I'm sorry, I just deleted my comment as I misread... I thought the new version was already deployed.

**Comment by stdedos** [comment]
As a side question: Is the message given wrongly-phrased?
I am on 203.* version, and it says:

> Incompatible: requires IDE build 203 or older

i.e. >= 203,* (let's assume decimals, it makes my argument easier)
So, `my 203,* >=  requires 203,*`... what gives? I would expect it would say e.g.:

> Incompatible: requires IDE build 202 or earlier

**Comment by ruurd** [comment]
OK I installed ...203 and that crashes Rubymine for some reason...

**Comment by hsz** [comment]
All right - I've prepared a release version for the plugin compatible with 2020.3.
Since it contains not only version bumped but also a bunch of refactorings and compatibility fixes to make it aligned to the IJ SDK 203 (as described in [Tweet](https://twitter.com/hszanowski/status/1335306406682103808) mentioned above), I'd like to ask you for a manual installation of the attached archive and checking if nothing is broken.
Thanks, folks!

[ignore-4.0.0.zip](https://github.com/JetBrains/idea-gitignore/files/5676429/ignore-4.0.0.zip)

**Comment by BorzdeG** [comment]
Why don't you want to set up an EAP publishing channel in plugins.jetbrains.com, the way JetBrains recommends?

**Comment by hsz** [comment]
@BorzdeG  I've prepared an [automated EAP release process](https://github.com/JetBrains/idea-gitignore/blob/refreshment/build.gradle.kts#L153) that depends on the version name - i.e. `v4.0.0-eap` will publish artifact to the `eap` channel instead to the `default` one.
Such GitHub integration is taken from the [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template#publishing-the-plugin).

For now, I didn't go that way simply because I care about the feedback collected here. The latest version published in EAP three years ago channel was downloaded 400+ times only.

**Comment by marcinsmialek** [comment]
It makes sense. It's too bad that getting EAP plugin versions is cumbersome. I'd use more of them in the past if they were easily accessible - like Rider EAP or prerelease NuGet packages.

**Comment by hsz** [comment]
In fact, I've published `4.0.0-eap` to the EAP channel this morning anyway.
@marcinsmialek Since now – having a properly working CI and fixing all the compatibility issues and integration with Plugin Verifier tool – providing the pre-releases will be much easier.
We'll include the EAP channel in the everyday work for that plugin.

**Comment by BorzdeG** [comment]
@marcinsmialek The EAP version of the plugin has nothing to do with the EAP version of the IDE - they can exist separately
