### ISSUE TITLE
Incompatible with 2022.3 EAP

### ISSUE THREAD

**Issue by erjotek** [JetBrains/idea-gitignore#784]
![image](https://user-images.githubusercontent.com/50953419/195452825-758519dc-fea3-4648-96e7-d3a3a1e3efd9.png)

**Comment by bloep** [comment]
You can use the channel `eap` as described here
https://github.com/JetBrains/idea-gitignore#early-access-preview

**Comment by erjotek** [comment]
I tried but it doesn't work:
![image](https://user-images.githubusercontent.com/50953419/195795279-7f347e49-2ad1-47f3-86ba-3a53bb2298e1.png)

**Comment by Scott-G** [comment]
Same problem here. EAP channel says "No plugins found"

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/200439544-e6fe420d-a6cf-4c58-8fd1-7b78b9e6df1c.png)

**Comment by Scott-G** [comment]
Any update on this from Jetbrains???

This is a great plugin but is useless to those of us who use the EAP whenever it is available (which is most of the time!). I don't have any other plugins that constantly have this issue.

It is PERMANENTLY incompatible with any EAP builds (seemingly by design) - and the plugin's EAP channel (mentioned above) does not work.

Please sort this out.

**Comment by bluelovers** [comment]
https://github.com/JetBrains/idea-gitignore/pull/789
