### ISSUE TITLE
Why can't I find the plugin in the marketplace?

### ISSUE THREAD

**Issue by YogiLiu** [JetBrains/idea-gitignore#797]
### Prerequisites

* [ ] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. Open File -> Settings -> Plugin
2. Search `.ignore`

**Expected behavior:**

Plugin named .ignore in list.

**Actual behavior:** 

Didn't find the plugin named .ignore.

**Reproduces how often:** 

100%

### Versions

**Plugin:** 

**IDE:** 

```
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to xxx
You have a perpetual fallback license for this version.
Subscription is active until xxx.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1912M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    mobi.hsz.idea.gitignore (4.4.2)
    Dart (222.4345.14)

Kotlin: 222-1.7.21-release-272-IJ4167.29
```

**OS:** 

```
Windows 11
```

### Additional Information

Visit https://plugins.jetbrains.com/plugin/7495  and also get 404 error.

**Comment by dj-rabel** [comment]
Experienced the same issue today with PhpStorm 2022.2.3

Funny enough it works with the version 4.4.1 and 4.4.2 of the plugin, if you install it manually.
https://github.com/JetBrains/idea-gitignore/releases/tag/v4.4.2

Hope this helps some people until this issue is resolved.

![image](https://user-images.githubusercontent.com/4653214/203377376-e68ee6c7-7597-41d5-b425-2096cd998039.png)

**Comment by hsz** [comment]
All the missing versions are now republished.
